### ISSUE TITLE
Heroku app not found

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#15]
The Heroku app not found (the link in README), also do you have the dev version on Heroku as well?

**Comment by JustinHsie** [comment]
Ah sorry I only changed the wiki, the README is updated now

**Comment by Exegetech** [comment]
@JustinHsie don't commit to master, create a branch first, with PR, then in the PR explains what the changes and what issue number is closed.

**Comment by JustinHsie** [comment]
Ok I'll do that in the future, I thought I could commit to master just for the README

**Comment by Exegetech** [comment]
This is not a hard and fast rule for sure, but in the future if you are working with bigger teams this will annoy people as it can break their git history if they decided to change the files that you are touching (in this case, README). Besides, once master is messed up, then you need to fix it, or your team lead needs to fix it.

Other problems, you might accidentally commit a sensitive info on the README, such as credentials like database password. This is why Pull Request Review is needed, more eyes to see if there are potential of sensitive information committed into history. If this is the case, you are in big trouble because git history can't be erased, so any attacker can just do a grep search throughyout your commit history and boom, they found out that at one point your README contains a database credentials, and the attacker has access to your database. In order to fix this you need to do a squash and git push force, which will make your teammates even more angry since now you are potentially hanging the entire repo history not just the README file. The only solution to redeem this is to remove the git entire history (which akin to remove the repository) altogether and reset from the start. You can always change your database password, but you also will invoke the anger of the entire org that depends on that database because now they need to change their password.

In general, always open a branch even for small PR. This is a good habit to have.
