### ISSUE TITLE
What should be next

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#16]
What should be next? Should we clean up the UI view first in general? I don't know what workflow works for you, but for me I usually try to cleanup the UI and to make it look nicer, because it distracts me if it doesn't look at least decent.

**Comment by JustinHsie** [comment]
Oh interesting haha! My instinct is to get it working and worry about the prettiness later, but I want to try this workflow! Let's clean up the UI view first

**Comment by Exegetech** [comment]
@JustinHsie Don't close the issue yet. Generally product manager or QA, not the engineer is the one that closes issue.

**Comment by JustinHsie** [comment]
Ok! I just didn't want to give you too much to do haha, good to know

In the future should I open issues? Or leave that to you?

**Comment by Exegetech** [comment]
Yeah just leave that to me. I'll be the product manager/QA here.
