### ISSUE TITLE
What are the features of the app

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#2]
What are the features of the app. What can a user do?

**Comment by JustinHsie** [comment]
Core functionality:
A user can
 - Search for a location (ex: restaurant) and save it to a list
 - Use their current location/enter a location to get the closest restaurants on the list
 - Get directions/map to the restaurants
 
Additional features:
 - Create multiple lists and conduct search in a specific list
 - Customize title, description, and personal rating when saving a restaurant
 - Share lists with other users
 - Import lists from other users
 - Comment on/interact with other users' lists

**Comment by Exegetech** [comment]
> Core functionality:
> A user can
> 
>     * Search for a location (ex: restaurant) and save it to a list
Ok
>     * Use their current location/enter a location to get the closest restaurants on the list
Ok
>     * Get directions/map to the restaurants
Ok
> 
> Additional features:
> 
>     * Create multiple lists and conduct search in a specific list
Ok 
>     * Customize title, description, and personal rating when saving a restaurant
Ok
>     * Share lists with other users
How does the workflow look like? 
>     * Import lists from other users
Ok 
>     * Comment on/interact with other users' lists
Ok

**Comment by JustinHsie** [comment]
> How does the workflow look like?

Maybe they can click a 'share' button that will let them search for the user they want to share with and request to 'send' it to them. Then the other user can 'accept' the list and it will be imported into their account

**Comment by Exegetech** [comment]
> > How does the workflow look like?
> 
> Maybe they can click a 'share' button that will let them search for the user they want to share with and request to 'send' it to them. Then the other user can 'accept' the list and it will be imported into their account

Cool, lets put this list of features onto wiki as well
