### ISSUE TITLE
Enable Create new list functionality

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#20]
Using just an in memory database (i.e, just use an object, an array, inside this app, that if refreshed the data doesn't persist, discuss below if you don't understand what an in memory database should look like), enable the functionality of Create New List.

- User should be able to create a new list
- Newly created list should appear on Home and on Select List dropdown
- User should be able to remove a list

**Comment by JustinHsie** [comment]
I don't think I've worked with an in memory database before, so I did some quick research on it but I have a couple questions:

- My first thought was to do this with Redux, so if a user creates a list then it updates the store. Would this work as a temporary solution until we set up a backend db?

- Or am I supposed to use something like Redis? That was one of the top results for in memory dbs, but it seems like overkill for something temporary

**Comment by Exegetech** [comment]
Yeah it looks like that Redux. What I mean by in memory database in this context is simply the memory in which your application reside. Basically to put it in practical terms. Create a singleton object where you can require anywhere in the app, and this singleton object will hold your data as long as the app lives, and when you refresh the page, or quit the app, this data gets wiped.

```
export class Database {
   constructor() {
      this.db = [] // can be an object can be an array, lets do array in this example
   }

   /**
   * Add an item to the database, return the id of the item)
   **/
   addItem(item) {
      this.db.push(item)
      return this.db.length - 1
   }

   getItem(index) {
      return this.db[index]
   }

   deleteItem(index) {
      // logic to delete item
   }

   updateItem(index) {
     // logic to update item
   }
}
```

That above is just to give you an idea. Redux store works similar like that above, and you can even separate this database and Redux store or just use Redux store to implement something similar above.

**Comment by JustinHsie** [comment]
Ah ok got it, thanks!! I'll give it a shot

**Comment by JustinHsie** [comment]
Also, kinda unrelated, but what are your thoughts on classical vs prototypal inheritance in JS? 

I've read that to get the most out of the functional aspects of JS you want to avoid classes. 
But class syntax is now built into JS (I know it's just syntactic sugar and still prototypal under the hood). 
React uses both class and functional components, and you used a class for this db example.

Should I not worry about it and just go ahead and use classes when it's convenient? 
Or should I try to think in a prototypal mindset and avoid classes if possible?

For reference, I'm more familiar with classes because I came from Java

**Comment by Exegetech** [comment]
JavaScript does not have classical inheritance like Java, it only has prototypal inheritance. JavaScript class keyword is just a syntactic sugar on top of prototypal inheritance.

Just use whatever your preference is, there is no place for dogma in Software Engineering. This isn't a religion. You need a good mix of both. Pure FP and is a disaster and so does pure OOP as well, at least that has been my experience so far, and I encounter these in seniors as well. I myself learned exotic functional languages such as Lisp, Elixir, Rust and Haskell over the years, alongside other more mainstream imperative/oop languages such as Java and Go.

The example above can be implemented in functional style, using closure.

```
function createDb() {
    const db = []

     function addItem(item) {
          db.push(item)
      }

     // etc
 
     return {
        addItem,
        // etc
     }
}
```

My code style, I prefer to use class for any logic that needs I/O related external dependencies, and use functions for pure utility code that does not have external dependencies. Because less typing.

```
class SomeService {
      constructor(db, dependency1, dependency2) { // I just inject db and other dependencies one time
          this.db = db
          this.dependency1 = dependency1
          this.dependency2 = dependency2
      }

      doSomething(someArgument) {
         // use this.db and other dependencies to do something
      }

      doSomeOtherThing(someOtherArgument) {
        // use this.db and other dependencies to do some other thing
      }
}
```
vs
```
function doSomething(db, dependency1, dependency2, someArgument) {
   // do something with db
}

function doSomeOtherThing(db, dependency1, dependency2, someOtherArgument) { // I just dont want to type db and other dependencies many times
  // do some other thing with db
} 
```

Readability and debugability are my priority.  Once you start using extreme FP it is really hard to debug and read, same with once you start using extreme OOP. Keep it simple. Pure FP in JS also consumes more memory and more CPU cycles (unlike other pure FP languages like Haskell that has compiler magic that spits out tight loop on those map reduce combinations therefore making it still performant). It is nothing of course but imagine you start doing 10000 records and every single time you do map reduce foreach map reduce foreach and it will get slow quick, and your memory requirement will be huge, and yes I've seen that. In OOP style, you also can't just mutate everything everywhere, making the code flow confusing. Separate pure methods (methods that just return value and dont modify anything in the class instance) and non pure methods (methods that modify something in the class instance).

**Comment by JustinHsie** [comment]
Thanks so much Christian!! I've really been wanting to get your opinion on this haha, I'm grateful for your insight

**Comment by Exegetech** [comment]
I also don't like React Hooks. To me it breaks my mental model of what I knew of programming. Its mental model is applicable on React only. Too much magic in React Hooks. I still use React functional components but for anything stateful I use class based React components. Readability over DRY any day. When DRY starts to degrade readability I choose readability always.

1. Readability
2. DRY
3. Performance

**Comment by JustinHsie** [comment]
Oh dang, really? That's good to know, I'll refactor the stateful components back to class components

**Comment by Exegetech** [comment]
> Oh dang, really? That's good to know, I'll refactor the stateful components back to class components

You can use whatever you want. If you google this issue the developers are split, but I think for newcomers they won't necessarily see why I think React hooks are bad. I just think that React hooks are too much magic and I don't like magic. A function should be stateless, how come  a functional component can be stateful? You can't do that in JS world. The only reason that works is because React itself is a runtime that do magic things under the hood. This happens a lot in Angular world but I already accepted that Angular does Angular things, but for React I prefer it to be simple and follow my intuition.

**Comment by JustinHsie** [comment]
Yeah I saw some of the magic as I was refactoring haha, hooks makes some things super easy. I think what you said makes sense though.

Anyway, I finished refactoring the stateful ones to class components LOL. The dev app should work and I made a pull request
