### ISSUE TITLE
Connect app with Google Map

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#25]

**Comment by JustinHsie** [comment]
So to get this working, I think I need to do these steps:
- Make requests from the frontend to the backend
- Have the backend make the API request to Google Maps to keep the API Key hidden in the backend
- Send the requested data back to the frontend

Does this look right?

**Comment by Exegetech** [comment]
> So to get this working, I think I need to do these steps:
> 
>     * Make requests from the frontend to the backend
> 
>     * Have the backend make the API request to Google Maps to keep the API Key hidden in the backend
> 
>     * Send the requested data back to the frontend
> 
> 
> Does this look right?

That's correct. Is the API key a private key based on what Google said? If not you can just put it in the front end, less trip.

**Comment by JustinHsie** [comment]
Oh yeah, you're right! Google just wants me to restrict it, not necessary to make it private.

**Comment by JustinHsie** [comment]
Jk LOL, I was very confused by all the APIs. I've been looking at it all afternoon, and I think Google actually encourages a hidden key. (if you're curious: https://developers.google.com/maps/api-key-best-practices#no_embed_apikey)

But since this is just a personal project, can I keep it in the front end? I think the chances of someone abusing my key would be very low.

Maybe put it in a .env file so at least it's not on Github? Although create-react-app will embed environment variables into the build anyway lol

Or will employers care if I take the extra step to have the backend make the API request?

**Comment by Exegetech** [comment]
> Jk LOL, I was very confused by all the APIs. I've been looking at it all afternoon, and I think Google actually encourages a hidden key. (if you're curious: https://developers.google.com/maps/api-key-best-practices#no_embed_apikey)
> 
Are you gonna get billed by this? If so your credit card will get billed by someone who is abusing this key.

Put the API Key on the backend on environment variable. Look at how Heroku does environment variable. Do not push any API key here even in the branch.

> But since this is just a personal project, can I keep it in the front end? I think the chances of someone abusing my key would be very low.
> 
Very high. There are bots running all over Github scraping API keys 365/24/7. They even scrape ALL of personal data (credit card numbers, API keys, passwords) from Git history as well so once it is committed and pushed to Github and merged into master then it is game over, you need to change the keys. Actually even Github itself has their own bots that will send you warning if they find that you have personal data in your repo. But the question is, is Github bot faster than hacker bots? And are you faster than hacker bots? You can make this repo private but you can't show it to your employer.

> Maybe put it in a .env file so at least it's not on Github? Although create-react-app will embed environment variables into the build anyway lol
> 
> Or will employers care if I take the extra step to have the backend make the API request?

I will definitely care 100%. Breach happens all the time and developers that do not take security practices seriously is a red flag, should and will get fired. Make security practices a habit.

**Comment by Exegetech** [comment]
After reading more, the Javascript API key needs to be in the frontend. See this https://stackoverflow.com/questions/39625587/how-do-i-securely-use-google-api-keys

**Comment by JustinHsie** [comment]
Ok thanks!! I saw a lot of opinions but wasn't sure what to do after comparing it to the docs

So in conclusion:
- It's unavoidable with Google Maps and the API key needs to be in the frontend.
- I need to restrict it on Google
- It won't work with environment variables (backend and Heroku)
- I will eventually push the API key to Github in my code

I don't have a billing account connected, so I won't be charged. 
And I had no idea about the Github bots...but I guess I shouldn't be surprised
