### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#3]
Let's discuss on these pertaining UI:
- Draw rough sketches in wireframe on what the user workflow would look like. What are the UI components required inside it? For example, calendars, buttons, forms, maps, etc.
- Look for ready-made UI framework (i.e, React Material, React Bootstrap, etc). Does the UI framework have ready-made solutions for the UI components we need above?

**Comment by JustinHsie** [comment]
Homepage: https://wireframe.cc/Dkd1Tx
Find Near Me: https://wireframe.cc/eww3sq
View a List: https://wireframe.cc/kbF8ew
Add new place: https://wireframe.cc/vyaj69

Rough first draft. Don't know how to integrate finding other users yet

**Comment by Exegetech** [comment]
> Homepage: https://wireframe.cc/Dkd1Tx
> Find Near Me: https://wireframe.cc/eww3sq
> View a List: https://wireframe.cc/kbF8ew
> Add new place: https://wireframe.cc/vyaj69
> 
> Rough first draft. Don't know how to integrate finding other users yet

Can you create a wiki and put those links there. Also design the URL path as well for each page.

For the UI framework, you can google various "React UI framework", and see which style do you like, and see if those framework contains the most complete ready-made components and grid system that you can use. Usually most of the UI framework out there already quite complete but they just strip the barebones for the free version and have the complete one on paid version. You might want to consider the framework with the most number of ready-made component on the free version as your choice.

**Comment by JustinHsie** [comment]
Ok thanks, I added it to the wiki along with the URL paths.
I'll research a framework and add it to the wiki

Edit: Chose Material UI
