### ISSUE TITLE
Add user and authentication mechanism

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#31]
Add user and all authentication mechanism (both backend and frontend):
- Register
- Login
- Logout
- Change Password
- Get Profile

Use regular email/password, not OAuth.

**Comment by JustinHsie** [comment]
Should I make the authentication from scratch or use Passport?

I can get started quicker from scratch, but will employers like Passport better bc it's more standard?

**Comment by Exegetech** [comment]
> Should I make the authentication from scratch or use Passport?
> 
> I can get started quicker from scratch, but will employers like Passport better bc it's more standard?

I just realized I've been not using Passport for a while lol. I forgot that such things even exist. All this time I just always coded my own authentication.

Most likely your own implementation of username and password will fail in a lot of scenarios, despite what blog posts on the internet tell you. 

You can use whatever you want. What type of authentication style are you going to use?

I think the decision to use Passport or not (for this project) boils down to:
- Learning, so you can learn the bits and pieces of authentication
- Speed, you want to focus on building the app

You can do whatever you want. 

As an employer, I can (not necessarily will) ask how authentication works, and it will be a positive point, showing that a candidate knows about security stuffs. But like 90% people out there, including engineers, don't care about this. I won't hold it to them if they don't know how it works.

**Comment by JustinHsie** [comment]
Lol ok cool, I'll do it on my own then! 

I wanna focus on building the app, learning and integrating Passport might take longer than I want to
