### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#4]
What are the models required in this app. Models are the "Nouns" of the apps. For example:

- User
- Restaurant
- Lists of the Restaurants
- List Comments

**Comment by JustinHsie** [comment]
- User (lists, location)
- Restaurant (location, notes, personal rating)
- Lists of Restaurants (restaurants, comments)
- Map (distance, directions)

**Comment by Exegetech** [comment]
Usually we define models are the data that we save into the database and control ourselves. So using that general rule of thumb:

>     * User (lists, location)
User data, User list, is indeed a model, but User location is not, since we are not saving it in the database but compute it on the fly when a User opens the app, or are we?
>     * Restaurant (location, notes, personal rating)
Looks good
>     * Lists of Restaurants (restaurants, comments)
Looks good
>     * Map (distance, directions)
Since this one is computed on the fly with an API, this is not a model

**Comment by JustinHsie** [comment]
> User data, User list, is indeed a model, but User location is not, since we are not saving it in the database but compute it on the fly when a User opens the app, or are we?

Ah I see, yes we're computing on the fly

**Comment by Exegetech** [comment]
> > User data, User list, is indeed a model, but User location is not, since we are not saving it in the database but compute it on the fly when a User opens the app, or are we?
> 
> Ah I see, yes we're computing on the fly

Cool lets put the models into wiki as well
