### ISSUE TITLE
What are the APIs needed

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#5]
What are external APIs needed for this app?

**Comment by JustinHsie** [comment]
Google Maps API:
- Restaurant Location
- User Location (current or entered)
- Distance from user to restaurants
- Search/autocomplete restaurant search (when adding new restaurant to list)
- Map/directions to restaurant (visual or external link)

**Comment by Exegetech** [comment]
> Google Maps API:
> 
>     * Restaurant Location
> 
>     * User Location (current or entered)
> 
>     * Distance from user to restaurants
> 
>     * Search/autocomplete restaurant search (when adding new restaurant to list)
> 
>     * Map/directions to restaurant (visual or external link)

Looks good, can you put this into the Wiki?
