### ISSUE TITLE
Separate Frontend and Backend route

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#7]
In the Wiki the routes are wrong. What you are putting in the wiki is a route for server side rendering app.

In an SPA, the frontend and backend routes are separate. Frontend routes is the route mapping to the page views, while backend API route is the actual routes where data manipulation happpens.

For example, frontend routes:
- home page "/"
- search "/search"
- view all lists "/lists" (this can also be just the homepage so no need to explicitly have this)
- create a new list "/lists/new"
- view a list "/lists/:id"
- edit a list "/lists:/:id/edit"
- view all restaurants "restaurants"
- view a restaurant "/restaurants/:id"

For example, backend routes:
- authentication: "/auth"
  - login: POST "/auth/login"
  - logout: POST "/auth/logout"
  - get user data: GET "/auth/user"
- api: "/api"
  - create a new list: POST "/api/lists"
  - edit a list: PUT or PATCH "/api/lists/:id"
  - delete a list: DELETE "/api/lists/:id"
  - get a list data: GET "/api/lists/:id"
  - get all lists: GET "/api/lists"
  - get all lists according to query parameter: GET "/api/lists?user=christian&title=myfavoriterestaurant"

**Comment by JustinHsie** [comment]
Oh shoot, sorry, I got them mixed up. I'll fix it now
