### ISSUE TITLE
Create app main layout

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#8]
Create app main layout and the home content such as:
- Navigation
- Body (when the user is visiting "/")
- Footer (if any)
- Sidebar (if any)

Just hardcode all data for now. Remember to use PR instead of pushing directly to master

**Comment by JustinHsie** [comment]
I created the app homepage and made a new branch and pull request. Please let me know if there is anything I should be doing differently with that process!

The app was made with a frontend framework called react-admin, the link is in the wiki

It took me awhile to learn how the framework works - is this too much framework? ie, should I be building more components by hand?

I followed their tutorial to get set up and it included API calls to jsonPlaceholder. Those became the automatically generated User and Posts links, I can work on customizing with our actual API calls later

I also added the custom navigation links (Home, Search, New List, New Place)

**Comment by Exegetech** [comment]
UI framework, like all framework, has their own abstractions. I personally don't like too much abstractions because it often leaky (you need to know implementation detail to use it, which defeats the purpose of a framework) and abstracting the wrong thing. I looked at React-Admin and I don't like it, particularly because:

- Ugly
- Too few ready-made components
- Too many useless stuffs (like GraphQL, REST wrapper etc) that I don't need
- No grid system

In general for UI framework I look into these (for free versions):
- Reasonably pretty
- A lot of ready-made components
- Grid system (though I can make my own using flexbox/css grid but I'd rather have it consistent from the start)

I'll just tell you what UI framework to use. Replace React-Admin with PrimeReact

https://www.primefaces.org/primereact/showcase/#/

**Comment by JustinHsie** [comment]
Ok! Yeah that makes sense, React-admin didn't feel too great. I'll replace it with PrimeReact, thanks so much for the rec!!

**Comment by Exegetech** [comment]
It comes with some free themes as well, so you can try which themes are free and change theme to it

**Comment by JustinHsie** [comment]
Ok I made the homepage with menu nav and displays the user's lists. The lists are clickable but I don't know if I want the click to edit the list or launch a search.  I figure I can decide later when I actually start routing stuff
